services:
  postgres-orders:
    image: postgres:17-alpine
    env_file: ./apps/orion-orders/.env
    volumes:
      - postgres-orders:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-catalog:
    image: postgres:17-alpine
    env_file: ./apps/orion-catalog/.env
    volumes:
      - postgres-catalog:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-payment:
    image: postgres:17-alpine
    env_file: ./apps/orion-payment/.env
    volumes:
      - postgres-payment:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-dispatch:
    image: postgres:17-alpine
    env_file: ./apps/orion-dispatch/.env
    volumes:
      - postgres-dispatch:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

      

  rabbit-mqueue:
    hostname: orion-rabbitmq
    image: rabbitmq:3-management  # Recomendo usar tag espec√≠fica
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit-mqueue:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  orion-redis:
    image: redis:7-alpine
    hostname: orion-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres-orders:
    driver: local
  postgres-catalog:
    driver: local
  postgres-payment:
    driver: local
  postgres-dispatch:
    driver: local
  rabbit-mqueue:
    driver: local
  redis_data:
    driver: local