services:
  postgres-orders:
    container_name: orion-db-orders
    image: postgres:17-alpine
    env_file: ./apps/orion-orders/.env
    volumes:
      - postgres-orders:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-catalog:
    container_name: orion-db-catalog
    image: postgres:17-alpine
    env_file: ./apps/orion-catalog/.env
    volumes:
      - postgres-catalog:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-payment:
    container_name: orion-db-payment
    image: postgres:17-alpine
    env_file: ./apps/orion-payment/.env
    volumes:
      - postgres-payment:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit-mqueue:
    container_name: orion-rabbitmq
    hostname: orion-rabbitmq
    image: rabbitmq:3-management  # Recomendo usar tag espec√≠fica
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit-mqueue:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres-orders:
    driver: local
  postgres-catalog:
    driver: local
  postgres-payment:
    driver: local
  rabbit-mqueue:
    driver: local